apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  # This is the name of the service
  selector:
    app: vulnapp-pod 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080   # exposed on your host as http://localhost:30080
  type: NodePort